name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
      - 'fix'
      - 'bug'
  - title: '🧹 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
      - 'dependencies'
      - 'documentation'
  - title: '🤖 CI/CD'
    labels:
      - 'github-actions'
      - 'ci'
  - title: '📱 Android'
    labels:
      - 'android'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'bugfix'
      - 'fix'
      - 'bug'
      - 'chore'
      - 'dependencies'
      - 'documentation'
  default: patch

template: |
  ## What's Changed

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
